### ISSUE TITLE
Not compatible with Version 4.30 of NOPCommerce

### ISSUE THREAD

**Issue by AppBotTech** [PayGate/PayWeb_NopCommerce_4#5]
Please update package to be compatible with version 4.30

**Comment by bruce-atkinson** [comment]
Note: Booked and pending.

**Comment by GodfreyHlongwane** [comment]
Good day, was there any traction on this?

**Comment by reinocom** [comment]
Hi Guys, I took V4.20 and made it work in V4.30

**Comment by justinheilbron** [comment]
> 
> 
> Hi Guys, I took V4.20 and made it work in V4.30

I've had to do the same. Is your option to use Sandbox work? For me, the test account numbers for "approved payments" all get declined. Can't seem to pinpoint the issue though.

**Comment by reinocom** [comment]
Sandbox is ticked
PaygateID= 10011072130
Encryption Key : secret

Do you get to the redirect page on checkout?

**Comment by bruce-atkinson** [comment]
Hi @reinocom & @justinheilbron,

Just a note that the 4.3 release is pending with a working sandbox.

Will update ASAP

**Comment by ghost** [comment]
Is there any further progress?

**Comment by bruce-atkinson** [comment]
Hi @justinheilbron @AppBotTech @GodfreyHlongwane @SighlentNite,

Please find https://github.com/PayGate/PayWeb_NopCommerce_4/releases/tag/v4.3.0
